### PR TITLE
add Dockerfile

### PR DESCRIPTION
**Pull request by 0x46616c6b**

### CODE REVIEW

**Comment by cgunning** [comment]
Hi, this looks great. I'll take some time to verify it during the next few days.

**Comment by 0x46616c6b** [comment]
Cool, if its stable for you, let me know and it would be great to combine it with the Docker Hub to build automatically if the master was updated.

**Comment by cgunning** [comment]
Yes i'm going to look into putting it up on Docker Hub. I will however probably keep manual triggered builds in order to keep the current versioning so that a version of a docker image corresponds to a release.

**Comment by cgunning** [comment]
I've had a chance to test this now and it looks great.

**Pull request merged**
