### PR TITLE
Migrate to Go modules

### PR DESCRIPTION
**Pull request by kyrias**
Go modules are easier to deal with and update, and helps to reduce the future growth of the repository size.

### CODE REVIEW

**Comment by roidelapluie** [comment]
please run go mod vendor and commit vendor ...

**Comment by kyrias** [comment]
Why vendor the dependencies when it's not necessary though?

**Comment by roidelapluie** [comment]
diff easily

**Comment by kyrias** [comment]
Well, if they decide that it's necessary for this to be merged I will, but I won't unless someone from the company explicitly says so, as I consider vendoring dependencies to be a horrid practice.

**Pull request closed without merging**
